let dataHotelCasino = [
    {
        id: "ho1",
        name: "Hilton Garden Inn",
        photo: ["https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/68/0e/5a/exterior.jpg?w=1100&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/4c/72/52/hilton-garden-inn-new.jpg?w=1200&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/68/0f/9b/barlounge.jpg?w=1100&h=-1&s=1" ], 
        capacity:  18000,
        citiId: "city1",
        userId:  "admin1", 
    },
    {
        id: "ho2",
        name: "Hotel Artemide",
        photo: ["https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/9d/77/93/entrance-hotel-artemide.jpg?w=1200&h=-1&s=1", "https://www.theexaminernews.com/examiner-news/wp-content/uploads/2020/09/680-empire-city.pnghttps://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/2d/d5/dd/ambrosia-rooftop-restaurant.jpg?w=1200&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/2d/d5/f5/ambrosia-rooftop-bar.jpg?w=1200&h=-1&s=1"],
        capacity:  10000,
        citiId: "city2",
        userId:  "admin1", 
    },
    {
        id: "ho3",
        name: "Grand Hyatt Berlin",
        photo: ["https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/22/da/21/grand-hyatt-berlin.jpg?w=1200&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/e3/b6/19/hotel-lobby.jpg?w=1200&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/3a/1a/3a/grand-king-room.jpg?w=1200&h=-1&s=1" ], 
        capacity:  4500,
        citiId: "city3",
        userId:  "admin1", 
    },
    {
        id: "ho4",
        name: "Andronis Luxury Suites",
        photo: ["https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/f3/3c/84/pool-outdoor.jpg?w=1100&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/f3/3c/7e/guest-room.jpg?w=1100&h=-1&s=1" ], 
        capacity:  6000,
        citiId: "city4",
        userId:  "admin1", 
    },
    {
        id: "ho5",
        name: "Holland Casino Amsterdam Centrum",
        photo: ["https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/fa/2f/21/holland-casino-amsterdam.jpg?w=1200&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/b0/7e/32/speelautomaten.jpg?w=600&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/b0/7e/33/koepelzaal.jpg?w=600&h=-1&s=1" ], 
        capacity:  12000,
        citiId: "city5",
        userId:  "admin1",  
    },
    {
        id: "ho6",
        name: "Park Hotel Tokyo",
        photo: ["https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/41/30/04/corner-king-room-tokyo.jpg?w=1200&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/a6/1c/74/thann-casa-room.jpg?w=1200&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/18/67/d6/artist-room-jomon.jpg?w=1200&h=-1&s=1" ], 
        capacity:  1500,
        citiId: "city6",
        userId:  "admin1",  
    },
    {
        id: "ho7",
        name: "Dear Hotel Madrid",
        photo: ["https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/68/0e/5a/exterior.jpg?w=1100&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/7b/8a/b9/premium-room.jpg?w=1200&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/54/94/68/dear-reception.jpg?w=1200&h=-1&s=1" ], 
        capacity:  18000,
        citiId: "city7",
        userId:  "admin1", 
    },
    {
        id: "ho8",
        name: "Hippodrome Casino",
        photo: ["https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/88/11/2e/hippodrome-casino.jpg?w=1200&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/ea/81/51/hippodrome-casino.jpg?w=1200&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/ea/80/23/hippodrome-casino.jpg?w=1200&h=-1&s=1"],
        capacity:  9000,
        citiId: "city8",
        userId:  "admin1", 
    },
    {
        id: "ho9",
        name: "Ibis Bangkok Riverside",
        photo: ["https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1d/c3/9b/98/exterior-view.jpg?w=1100&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1d/c3/9b/f3/miscellaneous.jpg?w=1100&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1d/c3/9b/ef/miscellaneous.jpg?w=1100&h=-1&s=1" ], 
        capacity:  4500,
        citiId: "city9",
        userId:  "admin1", 
    },
    {
        id: "ho10",
        name: "Kempinski Seychelles Resort",
        photo: ["https://dynamic-media-cdn.tripadvisor.com/media/photo-o/03/5b/03/5c/kempinski-seychelles.jpg?w=1200&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/03/5b/03/9b/kempinski-seychelles.jpg?w=1200&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/03/0c/ca/a8/kempinski-seychelles.jpg?w=1200&h=-1&s=1" ],
        capacity:  6300,
        citiId: "city10",
        userId:  "admin1", 
    },
    {
        id: "ho11",
        name: "Jupiter Lisboa Hotel",
        photo: ["https://dynamic-media-cdn.tripadvisor.com/media/photo-o/25/03/d8/ca/jupiter-lisboa-hotel.jpg?w=1200&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/25/a8/c1/41/rooftop-pool.jpg?w=1200&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/25/03/d7/f0/superior-room.jpg?w=1200&h=-1&s=1" ],
        capacity:  3900,
        citiId: "city11",
        userId:  "admin1",  
    },
    {
        id: "ho12",
        name: "Citybox Oslo",
        photo: ["https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/a0/28/06/lobby.jpg?w=1200&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/a0/28/52/lobby.jpg?w=1200&h=-1&s=1", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/a0/27/c4/lobby.jpg?w=1200&h=-1&s=1" ],
        capacity:  3800,
        citiId: "city12",
        userId:  "admin1",  
    }

]